### ISSUE TITLE
Some weights of Qwen2ForTokenClassification were not initialized

### ISSUE THREAD

**Issue by Y-Claw** [RAGEN-AI/RAGEN#93]
I encountered the following error when trying Qwen2.5 3B and 7B, how to deal with it? Thank you very much!

(TaskRunner pid=62643)   File "/opt/conda/envs/ragen/lib/python3.12/site-packages/torch/distributed/fsdp/fully_sharded_data_parallel.py", line 483, in __init__
(TaskRunner pid=62643)     _auto_wrap(
(TaskRunner pid=62643)   File "/opt/conda/envs/ragen/lib/python3.12/site-packages/torch/distributed/fsdp/_wrap_utils.py", line 101, in _auto_wrap
(TaskRunner pid=62643)     _recursive_wrap(**recursive_wrap_kwargs, **root_kwargs)  # type: ignore[arg-type]
(TaskRunner pid=62643)     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(TaskRunner pid=62643)   File "/opt/conda/envs/ragen/lib/python3.12/site-packages/torch/distributed/fsdp/wrap.py", line 545, in _recursive_wrap
(TaskRunner pid=62643)     wrapped_child, num_wrapped_params = _recursive_wrap(
(TaskRunner pid=62643)                                         ^^^^^^^^^^^^^^^^
(TaskRunner pid=62643)   File "/opt/conda/envs/ragen/lib/python3.12/site-packages/torch/distributed/fsdp/wrap.py", line 545, in _recursive_wrap
(TaskRunner pid=62643)     wrapped_child, num_wrapped_params = _recursive_wrap(
(TaskRunner pid=62643)                                         ^^^^^^^^^^^^^^^^
(TaskRunner pid=62643)   File "/opt/conda/envs/ragen/lib/python3.12/site-packages/torch/distributed/fsdp/wrap.py", line 545, in _recursive_wrap
(TaskRunner pid=62643)     wrapped_child, num_wrapped_params = _recursive_wrap(
(TaskRunner pid=62643)                                         ^^^^^^^^^^^^^^^^
(TaskRunner pid=62643)   File "/opt/conda/envs/ragen/lib/python3.12/site-packages/torch/distributed/fsdp/wrap.py", line 563, in _recursive_wrap
(TaskRunner pid=62643)     return _wrap(module, wrapper_cls, **kwargs), nonwrapped_numel
(TaskRunner pid=62643)            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(TaskRunner pid=62643)   File "/opt/conda/envs/ragen/lib/python3.12/site-packages/torch/distributed/fsdp/wrap.py", line 492, in _wrap
(TaskRunner pid=62643)     return wrapper_cls(module, **kwargs)
(TaskRunner pid=62643)            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(TaskRunner pid=62643)   File "/opt/conda/envs/ragen/lib/python3.12/site-packages/torch/distributed/fsdp/fully_sharded_data_parallel.py", line 509, in __init__
(TaskRunner pid=62643)     _init_param_handle_from_module(
(TaskRunner pid=62643)   File "/opt/conda/envs/ragen/lib/python3.12/site-packages/torch/distributed/fsdp/_init_utils.py", line 629, in _init_param_handle_from_module
(TaskRunner pid=62643)     _sync_module_params_and_buffers(
(TaskRunner pid=62643)   File "/opt/conda/envs/ragen/lib/python3.12/site-packages/torch/distributed/fsdp/_init_utils.py", line 1126, in _sync_module_params_and_buffers
(TaskRunner pid=62643)     _sync_params_and_buffers(
(TaskRunner pid=62643)   File "/opt/conda/envs/ragen/lib/python3.12/site-packages/torch/distributed/utils.py", line 334, in _sync_params_and_buffers
(TaskRunner pid=62643)     dist._broadcast_coalesced(
(TaskRunner pid=62643) torch.distributed.DistBackendError: NCCL error in: /pytorch/torch/csrc/distributed/c10d/NCCLUtils.hpp:268, unhandled cuda error (run with NCCL_DEBUG=INFO for details), NCCL version 2.21.5
(TaskRunner pid=62643) ncclUnhandledCudaError: Call to CUDA function failed.
(TaskRunner pid=62643) Last error:
(TaskRunner pid=62643) Cuda failure 1 'invalid argument'
Loading checkpoint shards: 100%|██████████| 2/2 [00:14<00:00,  7.41s/it] [repeated 3x across cluster]
(WorkerDict pid=63094) Some weights of Qwen2ForTokenClassification were not initialized from the model checkpoint at Qwen/Qwen2.5-3B-Instruct and are newly initialized: ['score.bias', 'score.weight'] [repeated 3x across cluster]
(WorkerDict pid=63094) You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

**Comment by Y-Claw** [comment]
I'm currently on main branch, commit 48822b04ad5db2ed651130b1703d948b1bd0d3d6 and installed ragen using `bash scripts/setup_ragen.sh`
When I tried to train Qwen-2.5-0.5B and Qwen-2.5-1.5B with the following code, it worked perfectly:
`
export HF_ENDPOINT=https://hf-mirror.com 
export MKL_SERVICE_FORCE_INTEL=TRUE

USE_PPO="algorithm.adv_estimator=gae" # by default.

python train.py --config-name _3_frozen_lake system.CUDA_VISIBLE_DEVICES=\"4,5,6,7\" trainer.n_gpus_per_node=4 trainer.experiment_name=frozen_lake-ppo-qwen2.5-1.5b-instruct actor_rollout_ref.rollout.rollout_filter_ratio=0.25 $USE_PPO model_path=Qwen/Qwen2.5-1.5B-Instruct
`

But when I try to change model_path to Qwen/Qwen2.5-3B-Instruct the error occurred:
`
export HF_ENDPOINT=https://hf-mirror.com 
export MKL_SERVICE_FORCE_INTEL=TRUE

USE_PPO="algorithm.adv_estimator=gae" # by default.

python train.py --config-name _3_frozen_lake system.CUDA_VISIBLE_DEVICES=\"4,5,6,7\" trainer.n_gpus_per_node=4 trainer.experiment_name=frozen_lake-ppo-qwen2.5-3b-instruct actor_rollout_ref.rollout.rollout_filter_ratio=0.25 model_path=Qwen/Qwen2.5-3B-Instruct $USE_PPO
`

**Comment by Y-Claw** [comment]
Thank you for your response and for maintaining this project. I’ve realized the issue was caused by the GPU cluster I was using — everything works fine now.
